name: sample-expressjs
services:
- environment_slug: node-js
  github:
    branch: main
    repo: digitalocean/sample-expressjs
  name: sample-expressjs
  build_command: npm install pm2 -g && npm install
  run_command: npm start